project_id = "tiounhhmliodkxqdqdog"

[functions.admin-delete-user]
verify_jwt = false

[functions.create-staff-user]
verify_jwt = false

[functions.update-staff-user]
verify_jwt = false

[functions.delete-staff-user]
verify_jwt = false

[functions.manage-role]
verify_jwt = false

[functions.manage-role-permissions]
verify_jwt = false

[functions.manage-role-inheritance]
verify_jwt = false

[functions.manage-user-roles]
verify_jwt = false

[functions.detect-ip]
verify_jwt = false

[functions.validate-shop-ip]
verify_jwt = false

[functions.place-order-secure]
verify_jwt = false
